apiVersion: apps/v1
kind: Deployment
metadata:
  name: eshop-web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: my-app
        # Burası Nexus'taki imaj adresin olacak
        image: nexus-server.local:8083/my-first-app:latest
        ports:
        - containerPort: 8080
        env:
        # 1. Mevcut değişkenlerin
        - name: CatalogBaseUrl
          value: "http://web-service" 

        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"

        # 2. YENİ EKLEYECEĞİNİZ: Bu hata için kritik olan değişken
        - name: PATH_BASE
          value: "/" 

        - name: ConnectionStrings__CatalogConnection
          value: "Server=sql-server-ip;Database=CatalogDB;User Id=sa;Password=admin;"
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  type: NodePort # LoadBalancer yerine NodePort yapıyoruz
  selector:
    app: web # Pod etiketlerinle aynı olmalı
  ports:
    - protocol: TCP
      port: 80         # Servis içi port
      targetPort: 8080   # Konteyner portu
      nodePort: 30080  # Dışarıdan erişeceğin sabit port (30000-32767 arası)