# ---------------- SQL SERVER DEPLOYMENT ----------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sql-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql
  template:
    metadata:
      labels:
        app: mssql
    spec:
      
      containers:
      - name: mssql
        image: mcr.microsoft.com/azure-sql-edge:latest 
        ports:
        - containerPort: 1433
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_SA_PASSWORD
          value: "GeciciSifre123!"
---
# A
# ---------------- SQL SERVER SERVICE ----------------
apiVersion: v1
kind: Service
metadata:
  name: sql-server-service
spec:
  selector:
    app: mssql
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
---
# ---------------- ESHOP WEB APP DEPLOYMENT ----------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eshop-web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: eshop-web
        image: nexus-server.local:8083/eshop-web:22 # Buradaki tag'i Jenkins'e göre kontrol et
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: PATH_BASE
          value: "/"
        - name: CatalogBaseUrl
          value: "/"

        # Hiyerarşiyi hem çift alt tire hem de düz isim olarak veriyoruz (Garanti olsun)
        - name: ConnectionStrings__CatalogConnection
          value: "Server=sql-server-service;Database=Microsoft.eShopOnWeb.CatalogDb;User Id=sa;Password=GeciciSifre123!;Encrypt=False;TrustServerCertificate=True;"
        - name: CatalogConnection
          value: "Server=sql-server-service;Database=Microsoft.eShopOnWeb.CatalogDb;User Id=sa;Password=GeciciSifre123!;Encrypt=False;TrustServerCertificate=True;"
        
        - name: ConnectionStrings__IdentityConnection
          value: "Server=sql-server-service;Database=Microsoft.eShopOnWeb.Identity;User Id=sa;Password=GeciciSifre123!;Encrypt=False;TrustServerCertificate=True;"
        - name: IdentityConnection
          value: "Server=sql-server-service;Database=Microsoft.eShopOnWeb.Identity;User Id=sa;Password=GeciciSifre123!;Encrypt=False;TrustServerCertificate=True;"


---
# ---------------- ESHOP WEB APP SERVICE ----------------
apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  type: NodePort
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080
