apiVersion: apps/v1
kind: Deployment
metadata:
  name: eshop-web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: my-app
        # Burası Nexus'taki imaj adresin olacak
        image: nexus-server.local:8083/my-first-app:latest
        ports:
        - containerPort: 80
        env:
        # 1. Çökmeye sebep olan boş URL'i dolduruyoruz
        - name: CatalogBaseUrl
          value: "http://web-service" 

        # 2. .NET'in Development modunda çalışmasını sağlıyoruz (hata detaylarını görmek için)
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"

        # 3. İleride alacağınız veritabanı hatasını önlemek için (Şimdilik boş bir SQL adresi)
        - name: ConnectionStrings__CatalogConnection
          value: "Server=sql-server-ip;Database=CatalogDB;User Id=sa;Password=admin;"     
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  type: NodePort # LoadBalancer yerine NodePort yapıyoruz
  selector:
    app: eshop-web-app # Pod etiketlerinle aynı olmalı
  ports:
    - protocol: TCP
      port: 80         # Servis içi port
      targetPort: 80   # Konteyner portu
      nodePort: 30080  # Dışarıdan erişeceğin sabit port (30000-32767 arası)